config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, controllers: { registration: "registrations" }

resources :books do
  resources :reviews
end
resources :messages do
  resources :comments
end
resources :users, :only => [:show]

resources :subscribers

 get "messages" => "messages#show"

 get "search" => "pages#search"

get "payment" => "pages#payment"

get "charge" => "pages#charge"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :book_img, :content_type => /\Aimage\/.*\Z/

 has_attached_file :book_document
    validates_attachment_content_type :book_document, content_type: ['image/jpeg', 'image/png', 'application/pdf']
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :messages
  has_many :comments
  has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :fullname, presence: true, length: {maximum: 50}

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :fullname
    devise_parameter_sanitizer.for(:account_update) << :fullname << :description << :email << :password << :avatar
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
	if params[:category].blank?
		@books = Book.all.order("created_at DESC")
	else
		@category_id = Category.find_by(name: params[:category]).id
		@books = Book.where(:category_id => @category_id).order("created_at DESC")
	end
end

def show
	if @book.reviews.blank?
		@average_review = 0
	else
		@average_review = @book.reviews.average(:rating).round(2)
end
end

def new
  @book = current_user.books.build
  @categories = Category.all.map{ |c| [c.name, c.id] }
end

def create
  @book = current_user.books.build(book_params)
  @book.category_id = params[:category_id]

  if @book.save
    redirect_to root_path
  else
    render 'new'
  end
end

def edit
  @categories = Category.all.map{ |c| [c.name, c.id] }
end

def update
  @book.category_id = params[:category_id]
  if @book.update(book_params)
    redirect_to book_path(@book)
  else
    render 'edit'
  end
end

def destroy
  @book.destroy
  redirect_to root_path
end

private

  def book_params
    params.require(:book).permit(:title, :description, :author, :category_id, :book_img, :book_document)
  end

  def find_book
    @book = Book.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_message
before_action :find_comment, only: [:edit, :update, :destroy]
before_action :authenticate_user!

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
  end
end

def destroy
@comment.destroy
redirect_to message_path(@message)
end

private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_message
      @message = Message.find(params[:message_id])
end

def find_comment
    @comment = @message.comments.find(params[:id])
end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show
  end

  def new
    @message = current_user.messages.build
end

def create
  @message = current_user.messages.build(message_params)
  if @message.save
  redirect_to messages_path
else
  render 'new'
end
end

def edit
end

def update
  if @message.update(message_params)
    redirect_to messages_path
  else
    render 'edit'
  end
end

def destroy
  @message.destroy
  redirect_to messages_path
end

private

def message_params
  params.require(:message).permit(:title, :description)
end

def find_message
  @message = Message.find(params[:id])
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_book
			@book = Book.find(params[:book_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  before_filter :authenticate_user!

  def new
  end

  def update
    token = params[:stripeToken]

    customer = Stripe::Customer.create(
    card: token,
    plan: 1020,
    email: current_user.email
    )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.save

    redirect_to root_path

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
     @user = User.find(params[:id])
     @reviews = @user.reviews
  end

  def show
  @user = User.find(params[:id])
  end

def new
  @avatar = current_user.avatar.build
  @avatar.build_photo
end

def create
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:fullname, :email, :password,
                                   :password_confirmation, :avatar)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
  gravatar_id = Digest::MD5::hexdigest(user.email).downcase
  "https://secure.gravatar.com/avatar/1c0948df53565f982c6efdfabfcfa537"
end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
<%= f.file_field :book_img %>
<%= f.file_field :book_document %>
<%= f.input :title, label: "Book Title" %>
<%= f.input :description %>
<%= f.input :author %>
<%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-book-form">

		<h1>Edit Book</h1>

		<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.file_field :book_img %>
			<%= f.file_field :book_document %>
			<%= f.input :title, label: "Book Title" %>
			<%= f.input :description %>
			<%= f.input :author %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>

</div>

app/views/books/index.html.erb
<body class="orange">

<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
<h1> There are no books currently in this category</h1>
<% else %>
<% @books.each do |book| %>
<a href="/books/<%= book.id %>">
  <%= image_tag book.book_img.url(:book_index), class: "book" %>
</a>
<% end %>
<% end %>
</body>

app/views/books/new.html.erb
<div id="newbook" class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
<h1>New book</h1>

<%= render 'form' %>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="row">

	<div class="col-md-4">

		<%= image_tag @book.book_img.url(:book_show), class: "book-show" %>

	</div>
  <div class="col-md-8">
<div class="book-info">

  			<h2 class="book-title"><%= @book.title %></h2>
  			<h3 class="book-author"><span>From</span> <%= @book.author %></h3>
        <h3>Average Rating</h3>
        <div class="average-review-rating" data-score=<%= @average_review %>></div>
					<span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>
				<p class="book-desc"><%= @book.description %></p>
				<div class="reviews">
					<h1>Reviews</h1>
		    <%= render @book.reviews %>
				<%= link_to "Add Review", new_book_review_path(@book), class: "btn btn-custom" %>
		    </div>
					<iframe id="iframebook" src=<%= @book.book_document if @book.book_document.present? %></iframe>
</div>
</div>
<div class="row">
  <div class="col-md-4">
			<iframe id="iframebook" src=<%= @book.book_document if @book.book_document.present? %></iframe>
	</div>
  </div>
</div>
</div>
<div class="links btn-group">
  <%= link_to "Back", root_path, class: "btn btn-custom" %>
  </div>

  <% if user_signed_in? %>

  <% if @book.user_id == current_user.id %>



  <%= link_to "Back", root_path, class: "btn btn-custom" %>
  <%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
  <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-custom" %>

  <% end %>

  <% end %>
</div>

  <script>
  	$('.review-rating').raty({
  		readOnly: true,
  		score: function() {
  			return $(this).attr('data-score');
  		},
  		path: '/assets/'
  	});
  </script>

  <script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/comments/_comment.html.erb
<div class="comment">
<p class="comment-content"><%= comment.content %></p>
<p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %></p>

<div class="links">
<% if user_signed_in? %>
<% if comment.user_id == current_user.id %>
<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
<% end %>
</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
<%= f.input :content, label: "Comment" %>
<%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
<%= f.input :content, label: "Comment" %>
<%= f.button :submit %>
<% end %>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
<%= f.input :title, label: "Message Title" %>
<%= f.input :description %>
<%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<body class="forum">
  <div class="messagehome">
<div class="col-md-8"
<div class="message">
</div>
</div>
<div class="col-md-6 pull-left">
<%= link_to "New Message", new_message_path, class: "btn btn-default pull-left" %>
</div>
<% @messages.each do |message| %>
<div class="col-md-6">
  <div class="message">
<h2 class="message-title"><%= message.title %></h2>
<%= link_to "View Message", message_path(message), class: "btn btn-default" %>
</div>
</div>
<% end %>
</div>
</body>

app/views/messages/new.html.erb
<body class="newmessage">
  <div class="newmessage1">
<div class="col-md-8 col-md-offset-2">
<h1> New Message </h1>

<%= render 'form' %>
</div>
</div>
</body>

app/views/messages/show.html.erb
<body class="black1">
<div class="col-md-8 col-md-offset-2">
  <div class="message-show">
<h2><%= @message.title %></h2>
<p class="message-posted-by">Posted by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago </p>
<p class="message-desc"><%= @message.description %></p>


<h3>Comments:</h3>
<%= render @message.comments %>

<h3 class="reply-to-msg">Reply to Message:</h3>
<%= render 'comments/form' %>
<div class="links btn-group">
<%= link_to "Back", messages_path(@message), class: "btn btn-default" %>
<% if user_signed_in? %>
<% if @message.user_id == current_user.id %>
<%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
<% end %>
<% end %>
</div>
</div>
</div>
</body>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
<div id="rating-form">
  <label>Rating</label>
</div>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"><%= review.comment %></p>

<% if user_signed_in? %>
<% if review.user_id == current_user.id %>

<div class="links btn-group">

<%= link_to "Edit", edit_book_review_path(review.book, review), class:"btn btn-custom" %>
<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-custom" %>
</div>
<% end %>

<% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@book, @review]) do |f| %>
<div id="rating-form">
  <label>Rating</label>
</div>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<body class="newreview">
<div id="newbook" class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
<h1> New Review </h1>
<%= render 'form' %>
</div>
</div>
</div>
</body>

app/views/users/show.html.erb
<body class="userprofile">
<div class="container">
<div class="row">
	<div class="col-md-3">
		<div class="center">
			<%= image_tag avatar_url(@user), class: "avatar-full" %>

			<% if current_user != @user %>
				<div class="row-space-2">
					<%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', class: "btn btn-primary wide" %>
				</div>
			<% end %>
			<div class="container">
				<div class="row">
				<div class="col-md-3">
					<h2><%= @user.fullname %></h2>
			  <div class="description row-space-3">
			    <h3>Bio </h3>
			    <%= @user.description %>
			  </div>
			</div>
			</div>
			</div>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">My Profile</div>
			<div class="panel-body">
			<div class="col-md-3">
	<%= @user.email %>
<br> <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-default wide" %> </br>
			</div>
		</div>
		</div>
	</div>
</div>

</div>
</body>