config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, controllers: { registration: "registrations" }

resources :books do
  resources :reviews
end
resources :messages do
  resources :comments
end
resources :users, :only => [:show]

resources :subscribers

 get "messages" => "messages#show"

 get "search" => "pages#search"

get "payment" => "pages#payment"

get "charge" => "pages#charge"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :book_img, :content_type => /\Aimage\/.*\Z/

 has_attached_file :book_document
    validates_attachment_content_type :book_document, content_type: ['image/jpeg', 'image/png', 'application/pdf']
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :messages
  has_many :comments
  has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :fullname, presence: true, length: {maximum: 50}

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
	if params[:category].blank?
		@books = Book.all.order("created_at DESC")
	else
		@category_id = Category.find_by(name: params[:category]).id
		@books = Book.where(:category_id => @category_id).order("created_at DESC")
	end
end

def show
	if @book.reviews.blank?
		@average_review = 0
	else
		@average_review = @book.reviews.average(:rating).round(2)
end
end

def new
  @book = current_user.books.build
  @categories = Category.all.map{ |c| [c.name, c.id] }
end

def create
  @book = current_user.books.build(book_params)
  @book.category_id = params[:category_id]

  if @book.save
    redirect_to root_path
  else
    render 'new'
  end
end

def edit
  @categories = Category.all.map{ |c| [c.name, c.id] }
end

def update
  @book.category_id = params[:category_id]
  if @book.update(book_params)
    redirect_to book_path(@book)
  else
    render 'edit'
  end
end

def destroy
  @book.destroy
  redirect_to root_path
end

private

  def book_params
    params.require(:book).permit(:title, :description, :author, :category_id, :book_img, :book_document)
  end

  def find_book
    @book = Book.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_message
before_action :find_comment, only: [:edit, :update, :destroy]
before_action :authenticate_user!

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
  end
end

def destroy
@comment.destroy
redirect_to message_path(@message)
end

private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_message
      @message = Message.find(params[:message_id])
end

def find_comment
    @comment = @message.comments.find(params[:id])
end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show
  end

  def new
    @message = current_user.messages.build
end

def create
  @message = current_user.messages.build(message_params)
  if @message.save
  redirect_to messages_path
else
  render 'new'
end
end

def edit
end

def update
  if @message.update(message_params)
    redirect_to messages_path
  else
    render 'edit'
  end
end

def destroy
  @message.destroy
  redirect_to messages_path
end

private

def message_params
  params.require(:message).permit(:title, :description)
end

def find_message
  @message = Message.find(params[:id])
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_book
			@book = Book.find(params[:book_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
     @user = User.find(params[:id])
     @reviews = @user.reviews
  end

  def show
  @user = User.find(params[:id])
  end

def new
  @avatar = current_user.avatar.build
  @avatar.build_photo
end

def create
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:fullname, :email, :password,
                                   :password_confirmation, :avatar)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
  gravatar_id = Digest::MD5::hexdigest(user.email).downcase
  "https://secure.gravatar.com/avatar/1c0948df53565f982c6efdfabfcfa537"
end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommuteBook</title>
    <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Inknut+Antiqua' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "assets/animate.css" %>

  </head>

  <body>

<nav id="transparent" class="navbar navbar-default">
  <div class="container">
  <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
    <%= link_to "Faebl", root_path, class: "navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-epxanded="false">Book Categories </a>
      <ul class="dropdown-menu" role="menu">
        <% Category.all.each do |category| %>
        <li class="<%= 'active' if params[:category] == category.name %>">
          				<%= link_to category.name, books_path(category: category.name), class: "link" %>
                      <li><% link_to "All Books", books_path, class: "link" %></li>
    </li>
    <% end %>
    <li><%= link_to "All Categories", books_path %></li>
  </ul>
</li>
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
</ul>
</li>
<% end %>
  <% if user_signed_in? %>
    <% else %>
    <li><%= link_to "Log In", new_user_session_path %></li>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-epxanded="false">Community <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
<li><%= link_to "Messaging Forum", messages_path %></li>
    <% end %>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-epxanded="false">
          <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
          <%= current_user.fullname %> <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
    <li><%= link_to "Add Book", new_book_path %></li>
      <li role="separator" class="divider"></li>
    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li role="separator" class="divider"></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-epxanded="false">Community <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
<li><%= link_to "Messaging Forum", messages_path %></li>
<% end %>
</div>
</div>
</div>
</nav>
  <%= render 'shared/message' %>
<div class="container">
    <%= yield %>
  </div>
  <footer class="footer1">
         <div class="container text-center">
             <div class="row copyright">
                 <div class="col-lg-12">
                     <p class="small">&copy; 2016 Anne Maree Calpito </p>
                 </div>
             </div>
         </div>
     </footer>
  </body>
</html>

app/views/pages/_books.html.erb
<div class="container">
  <div class="row">

      <% @books.each do || %>
      <div class="col-md-3">
        <div class="thumbnail">
          <% unless book.categories.count == 0 %>
            <%= link_to image_tag(book.categories.first.image.url), book %>
          <% end %>
            <div class="caption">
              <h3><%= link_to book.title.truncate(70), book %></h3>
                <p><%= book.description.truncate(100) %></p>
            </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Faebl Books</title>
    <meta name="description" content="Commute Book helps commuters connect, read learn" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
    <link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://s.mlcdn.co/animate.css">
  <body>
    <header id="first">
    <div class="intro-content">
      <div class="container"
      <div class="row">
        <div class="col-md-6 pull-left">
              <h1 class="hello animated slideInLeft">Unleash</h1>
              <h1 class="secondmain animated slideInLeft">Your inner</h1>
              <h1 class="thirdmain animated slideInLeft">Bibliophile</h1>
              <h2 class="subheading animated slideInLeft">Find and network with people who share your love of reading</h2>
              <div class="col-md-10 col-md-offset-2">
          </div>
        </div>
      </div>
    </div>
   <div class="col-md-4 mb-sm-30"><a href="http://localhost:3000/users/sign_up"><button id="introbutton" class="btn-ghost">Join Faebl today</button><a></div>
 <video id="video-background" autoplay="" loop="" class="fillWidth fadeIn wow collapse in" data-wow-delay="0.5s" poster="https://s31.postimg.org/6cbgszf7f/readingbackground.png">
             <source src="/assets/reading.mp4" type="video/mp4">Your browser does not support the video tag. I suggest you upgrade your browser.
        </div>
        </div>
         </video>
     </header>
     <section id="boxeshalf">
       <div class="group">
           <div class="lefthalf">
            <img src="/assets/dark1.png" alt="" />
           </div>
           <div class="righthalf">
             <div class="row">
             <div id="abouttext" class="text-center animated slideInRight">
             <h1 class="headingabout animated slideInRight"> What is Faebl? </h1>
             <p class="paragraphabout animated slideInRight"> Faebl is a community of readers and bibliophiles. Our mission is to help people find and share books they love and to encourage reading with the distribution of ebooks.</p>
<h3 class="secondheading animated slideInRight">A few things you can do on Faebl</h3>
<p class="paragraphabout animated slideInRight">
 •	See which books your friends are reading.
 •	Download and read from our collection of ebooks.
 •	Track the books you're reading, have read and want to read.
 •	Check out your personalised book recommendations.
 •	Review books and find out if a book is a good fit for you from our community’s reviews.
 •	Provide self-publishing routes for contemporary authors.
 </p>
 </div>
 </div>
 </div>
 </div>
           </div>
       </div>
</section>
<!--new section-->
    <!-- Top books -->
    <section id="fourth1" class="container section ft-centered">
    <div class="container">
        <h2 id="popular" class="text-center animated slideInLeft">Most Popular Books</h2>
                  <!-- Item 1 -->
                  <div class="col-md-3 col-sm-6 mb-sm-50">
                    <div class="et-strategy">
                      <a href="http://localhost:3000/books/15">
               <img class="books1 animated slideInLeft" src="assets/warpeace.png"></img>
             </a>
                    </div>
                  </div>

                  <!-- Item 2 -->
                  <div class="col-md-3 col-sm-6 mb-sm-50">
                    <div class="et-strategy">
                        <a href="http://localhost:3000/books/16">
                        <img class="books1 animated slideInLeft" src="assets/pride.png"></img>
                      </a>
                       </div>
                  </div>

                  <!-- Item 3 -->
                  <div class="col-md-3 col-sm-6 mb-sm-50">
                    <div class="et-strategy">
                      <a href="http://localhost:3000/books/17">
                        <img class="books1 animated slideInRight" src="assets/sherlock.png"></img>
                      </a>
                       </div>
                  </div>

                  <!-- Item 4 -->
                  <div class="col-md-3 col-sm-6 mb-sm-50 ft-item>
                    <div class="et-strategy">
                          <a href="http://localhost:3000/books/14">
                        <img class="books1 animated slideInRight" src="assets/tale2.jpg"></img>
                      </a>
                       </div>
                  </div>
                    <div>
                </div><!-- / .row -->
              </section><!-- / .ft-frames -->
              <!-- Top books -->
              <section id="fourth1" class="container section ft-centered">
              <div class="container">
                            <!-- Item 1 -->
                            <div class="col-md-3 col-sm-6 mb-sm-50">
                              <div class="et-book">
                                  <a href="http://localhost:3000/books/18">
                         <img class="books1 animated slideInLeft" src="assets/metamorphosis.jpg"></img>
                       </a>
                              </div>
                            </div>

                            <!-- Item 2 -->
                            <div class="col-md-3 col-sm-6 mb-sm-50">
                              <div class="et-book">
                                  <a href="http://localhost:3000/books/19">
                                  <img class="books1 animated slideInLeft" src="assets/earnest.jpg"></img>
                                </a>
                                 </div>
                            </div>

                            <!-- Item 3 -->
                            <div class="col-md-3 col-sm-6 mb-sm-50">
                              <div class="et-book">
                                  <a href="http://localhost:3000/books/21">
                                  <img class="books1 animated slideInLeft" src="assets/victor.jpg"></img>
                                </a>
                                 </div>
                            </div>

                            <!-- Item 4 -->
                            <div class="col-md-3 col-sm-6 mb-sm-50">
                              <div class="et-book">
                                <a href="http://localhost:3000/books/20">
                                  <img class="books1 animated slideInLeft" src="assets/sense.jpg"></img>
                                </a>
                                 </div>
                            </div>
                              <div>
                          </div><!-- / .row -->
                        </section><!-- / .ft-frames -->
            <!--another carousel-->
            <section id="fourth1" class="container section ft-centered">
            <div class="container">
                <h2 id="popular" class="text-center animated slideInRight">Most Popular Genre: Classics</h2>
                          <!-- Item 1 -->
                          <div class="col-md-3 col-sm-6 mb-sm-50">
                            <div class="et-book">
                                <a href="http://localhost:3000/books/8">
                       <img class="books1 animated slideInLeft" src="assets/count.png"></img>
                                </a>
                            </div>
                          </div>

                          <!-- Item 2 -->
                          <div class="col-md-3 col-sm-6 mb-sm-50" data-wow-duration=".6s">
                            <div class="et-book">
                              <a href="http://localhost:3000/books/7">
                                <img class="books1 animated slideInLeft" src="assets/middle.png"></img>
                              </a>
                              </div>
                          </div>

                          <!-- Item 3 -->
                          <div class="col-md-3 col-sm-6 mb-sm-50" data-wow-duration=".6s">
                            <div class="et-book">
                                <a href="http://localhost:3000/books/10">
                                <img class="books1 animated slideInLeft" src="assets/villette.png"></img>
                              </a>
                               </div>
                          </div>

                          <!-- Item 4 -->
                          <div class="col-md-3 col-sm-6 mb-sm-50" data-wow-duration=".6s">
                            <div class="et-book">
                                <a href="http://localhost:3000/books/14">
                                <img class="books1 animated slideInLeft" src="assets/tale2.jpg"></img>
                              </a>
                               </div>
                          </div>
                            <div>
                        </div><!-- / .row -->
                      </section><!-- / .ft-frames -->
        <!--end of carousel-->
                        <section id="sixth">
                          <div class="container">
                                  <h3 id="popular" class="text-center animated slideInLeft">Thinking of self-publishing? Read recent success stories</h3>
                            </div>
                          </div>
                        </section>
                        <section id="carousel1">
                          <div id="carousel-example" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                        <li data-target="#carousel-example" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example" data-slide-to="1"></li>
                        <li data-target="#carousel-example" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                        <div class="item active">
                          <a href="#"><img src="/assets/magenta.png" /></a>
                          <div class="carousel-caption">
                            <h3>Alan McKinnon</h3>
                            <p>Author of <i>Road to Enlightenment</i></p>
                          </div>
                        </div>
                        <div class="item">
                          <a href="#"><img src="/assets/blueorange.png" /></a>
                          <div class="carousel-caption">
                            <h3>Angus Lowe</h3>
                            <p>Author of <i>Sombre and Sober</i></p>
                          </div>
                        </div>
                        <div class="item">
                          <a href="#"><img src="/assets/greenorange.png" /></a>
                          <div class="carousel-caption">
                            <h3>Alastair Craig</h3>
                            <p>Author of <i>Escape from Reality</i></p>
                          </div>
                        </div>
                        </div>

                        <a class="left carousel-control" href="#carousel-example" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                        </div>
                        </section>
     <section id="fifth">
       <div class="container">
         <div class="row">
           <div class="col-md-8">
           </div>
         </div>
       </div>
   </section>
  </body>
</html>

app/views/pages/payment.html.erb
<h1> helloooo </h1>



          <form action="/charge" method="POST">
            <script
              src="https://checkout.stripe.com/checkout.js"
              class="stripe-button"
              data-key="pk_test_6pRNASCoBOKtIshFeQd4XMUh"
              data-image="/square-image.png"
              data-name="Donate"
              data-description="Donate ($20.00)"
              data-amount="2000">
            </script>
          </form>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
<script type="text/javascript">
<% resource.errors.full_messages.each do |msg| %>
toastr.error('<%= msg %>')
<% end %>
</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
<% flash.each do |f| %>
<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
toastr['<%= type %>']('<%= f[1] %>')
<% end %>
</script>
<% end %>